# Generated by Django 4.2.7 on 2024-01-18 11:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_alter_userprofile_activity_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('weigth_progress', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), size=None)),
                ('weigth_Goal', models.FloatField(null=True)),
                ('workout_progress', models.IntegerField()),
                ('userfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['progress_id'],
            },
        ),
    ]
